### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by yanzhaobiomath** [VingronLab/APL#12]
Hi there,

I just tried to install APL on a machine with no other R packages installed (except devtools of course).  Then I got the following error message:

ERROR: dependencies ‘reticulate’, ‘Matrix’, ‘irlba’, ‘ggrepel’, ‘ggplot2’, ‘plotly’, ‘Seurat’, ‘SingleCellExperiment’, ‘SummarizedExperiment’ are not available for package ‘APL’
* removing ‘/home/.conda/envs/valis/lib/R/library/APL’
There were 30 warnings (use warnings() to see them)

Hope this message is useful for refine the dependencies of our package.

Best,
Yan

**Comment by ClemensKohl** [comment]
Thanks for letting me know! Could you post the code you ran to install it (branch etc.)? If you used devtools I believe it cannot install Bioconductor packages.

**Comment by yanzhaobiomath** [comment]
It's actually the branch for cabinet:
devtools::install_github("VingronLab/APL", ref = "cabinet-freeze")

**Comment by ClemensKohl** [comment]
All changes are now merged into the latest Bioconductor 3.20 release and it should be possible to install from there.
