### ISSUE TITLE
package ‘APL’ is not available (for R version 4.0.1) 

### ISSUE THREAD

**Issue by afederico-sci** [VingronLab/APL#2]
Hi,

Thanks a lot for developing such a nice package!
I would like to install in on my R (version 4.0.1), but it says that it is not available for my version:

package ‘APL’ is not available (for R version 4.0.1) 

Also, when I tried to install it via github, it says:
ERROR: this R is version 4.0.1, package 'APL' requires R >= 4.2

Since the R 4.2 was only very recently released and considering that the session info of your vignette reports that you worked on R 4.0.3, could you please indicate a solution to install APL in my current R version?

Thank you very much.

**Comment by ClemensKohl** [comment]
Hi !
Sorry for the inconvenience, the package is hopefully to be released with the next Bioconductor release and for that we had to set the R version requirements to 4.2.
But it should also work for 4.0.1 and there is a simple workaround:
Download the package by running `git clone https://github.com/VingronLab/APL.git` in a directory of your choice and then edit in the DESCRIPTION file the line 54 `Depends: R (>= 4.2)` to `Depends: R (>= 4)` or to your version in use.

You should have then no problem installing the package with `devtools::install(pkg = "/path/to/package")`.
Let us know if something does not work!

**Comment by afederico-sci** [comment]
Hi,

Thanks a lot for the fast reply and for the valuable suggestions. 

I followed them and it worked with only few edits:

`Depends: R(>= 4.0)` (it did not worked with just "4");
`devtools::install_local("/path/of/cloned/git/")`

It now worked perfectly. Thanks a lot!

**Comment by ClemensKohl** [comment]
Thanks for the feedback! Sorry for the mistakes in the post, I maybe should have tested it before :)
