### ISSUE TITLE
installation instructions in vignette are lacking a call to use_condaenv

### ISSUE THREAD

**Issue by malcook** [VingronLab/APL#3]
I think the following is required for an R session to use the installed conda environment, and should be included in your vignette.

```
use(reticulate)
use_condaenv(condaenv = file.path(miniconda_path(),"envs/r-reticulate")
           , required=TRUE # force usage of associated python 
             )
```

**Comment by ClemensKohl** [comment]
Thanks for spotting it! We are preparing an update to the package and will update the vignette with it!

**Comment by ms-gx** [comment]
Do I place above commands into .Rprofile and load? Can you explain a bit?
Thanks!

**Comment by ClemensKohl** [comment]
You can in principle put it into the .Rprofile if you always want to use the same environment, but it should be enough to just call it within your R session. In principle "r-reticulate" is the default environment, so it might not even be necessary, although it  ensures that you have the correct environment running.
So installation of the python dependencies should be possible by running:

```
library(reticulate)
install_miniconda()
use_condaenv(condaenv = file.path(miniconda_path(),"envs/r-reticulate"),
             required=TRUE)
      
conda_install(envname = "r-reticulate", packages = "numpy")
conda_install(envname = "r-reticulate", packages = "pytorch")
```
Later, whenever you load the package you can additionally ensure that the correct environment is being used by reticulate by calling
```
use_condaenv(condaenv = file.path(miniconda_path(),"envs/r-reticulate"),
             required=TRUE)
```

In my testing reticulate correctly used the "r-reticulate" environment by default, but it might be necessary for you depending on your setup. Should you continue to run into problems, you can still use the package without any python code by turning python=FALSE wherever applicable (it should be by FALSE by default). 
If you are getting an error, could you share the error message please?
