### ISSUE TITLE
Counts VS LogCounts

### ISSUE THREAD

**Issue by ms-gx** [VingronLab/APL#7]
What is your take regarding usage of raw counts (`counts` in Seurat) VS logcounts (`data` in Seurat) when running APL?

Do you have any recommendations? Or do you think that APL should produce about the same results and this choice does not make a huge difference, especially the high scoring genes?

**Comment by ClemensKohl** [comment]
We generally recommend using the logcounts, but it would not be wrong to use the counts. I did not perform a comprehensive benchmarking of counts vs logcounts on the APL results, so I cannot guarantee that one is definitely better than the other, but in my personal experience logcounts worked well. Going on discussions in literature about logcounts and correspondence analysis they should perform very similar (https://doi.org/10.1101/2021.11.24.469874).

**Comment by ms-gx** [comment]
Thanks much. This is really helpful. Thanks for the paper as well.

Maybe in this case you should consider to make` count = data` the default in `runAPL()`?
