### ISSUE TITLE
Genes downregulated in only one cluster

### ISSUE THREAD

**Issue by ms-gx** [VingronLab/APL#8]
Is there a way to detect genes which are **down**regulated in only one cluster using APL?

**Comment by ClemensKohl** [comment]
Hi Michael,

The short answer is no, there is unfortunately currently no way to detect downregulated genes. 

The long answer is that its a bit complicated. For simpler data (so not scRNAseq) I think it would be possible by "flipping" the input matrix such that high counts are low and low counts are high values (e.g., subtract row-wise max and take absolute value). But as scRNA-seq is so sparse and therefore mostly comprised of 0s, I am unsure what such a transformation would change about general properties of the data. So at the current moment I would definitely not recommend using such an approach!

Maybe in future updates we can think about adding such a functionality after testing it rigorously, but for the time being we can only detect upregulated genes.

**Comment by ms-gx** [comment]
Thanks much, closing issue
